### ISSUE TITLE
video stops loading and freezes when using Dark Reader extension on youtube

### ISSUE THREAD

**Issue by Tracenji** [WesselKroos/youtube-ambilight#226] opened 2024-03-20 17:32 UTC
### Bug description

the video timestamp freezes which causes youtube to not buffer more of the video but video still plays

### Steps to reproduce the behavior

have ambient light installed and enabled
have Dark Reader extension (version 4.9.80) installed and enabled on youtube
play a video, select 1440p60 quality, watch video
then timestamp freezes and video stops buffering new parts and buffer runs out

### Browser

Firefox

### Operating system

Linux

### Extension version

2.38.1

### The bug still happens in these conditions

- [ ] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [x] When I logged out of my YouTube account (ex. in incognito mode)
- [x] In incognito mode

### Additional context and/or screenshots

this seems like it only or at least mostly happens on 1440p quality
interacting with the youtube player, such as pausing/playing or otherwise causes it to buffer a small bit of the video again but freezes again

**Comment by WesselKroos** [comment] 2024-03-20 18:11
I'm unable to reproduce this issue (on Windows, because I don't have Linux).
But Firefox versions 123 and 124 have a performance regression bug (#224) So, theoretically, I could imagine that it takes up more CPU/GPU power that your system also needs to download and decode the video.

Could you check if this issue also exists on Firefox 122? Here you can download the older version:
https://support.mozilla.org/en-US/kb/install-older-version-firefox#w_i-still-want-to-downgrade-where-can-i-get-the-previous-version

**Comment by Tracenji** [comment] 2024-03-21 21:03
i did some more digging on Firefox 123 and it seems to only happen with many tabs/windows open (307 tabs over 14 windows if you were wondering, i know, i know, i should get rid of at least 90% of them)
so it seems to be performance related, it could be that Dark Reader combined with Ambient Light causes increased CPU/GPU power usage and combined with the regression in #224 causes it to not have enough CPU/GPU power left for video buffering
i do not believe i ever experienced this before Firefox 123, even with more tabs open than currently

i could still try checking if i am able to recreate this in Firefox 122 if you want

**Comment by WesselKroos** [comment] 2024-03-21 22:00
Ah, that's indeed a lot of tabs. Then I think we can be almost sure that it is performance related.

Then this should also be fixed once I have released version 2.38.2 which contains a workaround for Firefox 123 and 124. I'll probably do that in 1 or 3 days when I've found some spare time.

**Comment by WesselKroos** [comment] 2024-04-28 16:57
@Tracenji Firefox have fixed the performance regression in version 125. Could you check if you still have this problem in Firefox 125?

**Comment by WesselKroos** [comment] 2024-04-29 20:39
Strange, I improved nothing regarding the performance in the new extension version. Maybe they fixed something in Firefox 124 then.
Anyway, nice to hear that it has been fixed!

**Closed** 2024-04-29 20:39 UTC
Labels: B: Firefox, T: Performance
