### ISSUE TITLE
Washed out blacks on HDR monitor

### ISSUE THREAD

**Issue by Askejm** [WesselKroos/youtube-ambilight#248] opened 2024-06-15 13:38 UTC
### Bug description

When I enable ambient lights, blacks appear washed out on both HDR and non-HDR videos.

### Steps to reproduce the behavior

1. Enable HDR on a HDR capable monitor
2. Go to any video, HDR or not 
3. Compare blacks with ambient lights on and off 

### Browser

Firefox

### Operating system

Windows

### Extension version

2.38.9

### The bug still happens in these conditions

- [ ] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

### Additional context and/or screenshots

https://github.com/WesselKroos/youtube-ambilight/assets/55248977/2d7be61b-2ef6-4006-903e-21435977bdee
monitor: AW3423DWF
It doesn't happen on my non HDR monitor. The effect only appears in modes where ambient light is enabled (fullscreen and theater for me, but when its in windowed the effect doesnt appear)

**Comment by Askejm** [comment] 2024-06-15 13:40
https://github.com/WesselKroos/youtube-ambilight/assets/55248977/178357e7-f6a0-4a3c-9c8d-48766b26dccd

**Comment by WesselKroos** [comment] 2024-06-15 16:22
I think you might have missed #129

**Comment by WesselKroos** [comment] 2024-06-15 16:37
Duplicate of #129

**Closed by WesselKroos** 2024-06-15 16:37 UTC
Labels: T: Bug, S: Todo
