### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by artisticfox8** [WesselKroos/youtube-ambilight#98] opened 2021-10-30 09:40 UTC
**Is your feature request related to a problem? Please describe.**
I found Firefox workarounds in the code, while the extension is Chromium only right now (Edge, Chrome, etc.) 

**Describe the solution you'd like**
You release the extension to addons.mozilla.org and make it available for Firefox
**Describe alternatives you've considered**
I've tried loading the extension temporarily in Firefox and there is no extension button on YouTube https://www.youtube.com/watch?v=XxwtYIKI9dE and no errors in DevTools  So it looks like you detect Firefox and the extension is not running

**Additional context**
I use Firefox 93.0
![Snímek obrazovky (1486)](https://user-images.githubusercontent.com/77014769/139528004-675ebecc-a77a-41f9-969b-4eaa98de78e2.png)

**Comment by artisticfox8** [comment] 2021-10-30 09:45
The only error in about:devtools-toolbox is that you didn't set <meta charset="UTF-8"> and that you can't use characters outside US-ASCII because of that

**Comment by WesselKroos** [comment] 2021-10-30 12:10
> I found Firefox workarounds in the code, while the extension is Chromium only right now (Edge, Chrome, etc.)
I did support Firefox a year ago, but I stopped supporting it because of performance problems which kept on getting worse with each Firefox update. For example, a video with a framerate of 30 fps will drop down to 15 fps because the ambilight effect is rendered. I'll never be able to fix it because it is a performance problem in Firefox. That's why I've create a bugreport for my problem at Mozilla https://bugzilla.mozilla.org/show_bug.cgi?id=1673168 They have also bundled all the canvas performance problems in a single bugreport and lowered the priority to P3 a year ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1666271 So I don't think these performance problems will be fixed any time soon. But once they've fixed it I'll make sure to try it again.

> The only error in about:devtools-toolbox is that you didn't set `<meta charset="UTF-8">` and that you can't use characters outside US-ASCII because of that

That's an error caused by YouTube, I don't do anything with meta tags.

> So it looks like you detect Firefox and the extension is not running
That's not true. It could be that something was changed in the YouTube site layout for Firefox, or I could have added new features over the last year that might have broken it on Firefox. I stopped testing it on Firefox, so I don't know when it got broken. But feel free to debug and fix the code. If you fixed it I'm willing to add the fix to the codebase so that you can use the latest version. But I won't release it to the Firefox addons site because of the performance issues.

**Comment by Deagan** [comment] 2021-12-08 04:41
Shucks, could you help me install Ambilight on Firefox with it removed from the Addons Store? I have downloaded the source code ZIP, but I am unsure how to add it to Firefox Developer Edition? Also, I see that the latest release on Github is from 2020, was there any way to install the latest version on Firefox?

**Comment by WesselKroos** [comment] 2021-12-12 12:28
@Deagan 
Follow steps 1 and 2 in the Development section of the Readme.md: 
https://github.com/WesselKroos/youtube-ambilight#development

Then the easiest way to temporary install the extension is via the steps in Mozilla's Installing section. But the extension will be disable after a restart of Firefox: 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing

There is a way to permanently install an extension by signing it, but I havent tried that myself. You might find more info about it on this page:
https://extensionworkshop.com/documentation/publish/distribute-sideloading/

**Comment by Deagan** [comment] 2021-12-12 21:27
Thank you, I was able to test it again by building the source code!

Unfortunately the performance issues persist, mainly the video buttons lagging (video quality settings button, theater mode, etc), while the actual Ambilight effect itself seems to work well on my PC.

I will continue to use Ambilight on Brave instead, although I'd prefer it on Firefox. Thank you for your hard work and the awesome extension!

**Comment by WesselKroos** [comment] 2022-01-23 13:00
For anyone who wants to use the extension on Firefox in the future:
Google Chrome has started to enforce extensions to use Manifest V3, therefore I'm forced to implement Manifest V3 which means that from version 2.36.19 the extension won't work anymore in Firefox.

However, you can easily make the extension work again for any future versions by reverting the changes that have been made for Manifest V3 in this commit:
e39ef7af2a04a46310867e3e46ed985db5b0e48d

**Comment by WesselKroos** [comment] 2022-01-27 17:59
I might have found a way to get more performance in Firefox, and I'll have to support Manifest V2 for Opera as well. So I might bring back the Firefox Addon once I've implemented it.

**Comment by WesselKroos** [comment] 2022-03-13 22:00
@Deagan @artisticfox8 I've implemented a bunch of performance improvements for low-end devices the last few weeks, which should also improve the performance on Firefox. Would you be willing to test them out?

1. You can download the test version from this branch: https://github.com/WesselKroos/youtube-ambilight/tree/feature/webgl-projector.
2. Then follow steps 1 and 2 in the Development section of the Readme.md:
https://github.com/WesselKroos/youtube-ambilight#development
3. Then the easiest way to temporary install the extension is via the steps in Mozilla's Installing section. But the extension will be disable after a restart of Firefox:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing
4. For the optimal performance make sure that the settings outlined in red are set accordingly:
![image](https://user-images.githubusercontent.com/31220528/158080664-3bd4fa93-fcf5-4efc-a1ac-2cf14622b550.png)

Some of the things that should be noticeable is that a high **Blur**, high **Spread** and low **Edge size** setting should have almost no impact anymore. While earlier it had a large impact on the overall performance. The quality of the effect should stay similar as long as the **Blur** setting is high than 9.4%.

Let me know what the experience is like regarding the performance and the quality. If everything seems well enough I could plan a release to the Firefox Addons store.

**Comment by Deagan** [comment] 2022-03-14 04:32
Awesome, I have tested it on Firefox, and it's working great! The only thing I have noticed, while moving all of my settings from Chrome, is that the "Smooth Motion" feature doesn't work on Firefox. Smooth Motion seems to flicker on/off constantly instead of blurring between frames. Without this feature, it seems that the Firefox version is a bit more jittery, but overall, it is a rather smooth and working experience!

In testing this version on my RTX 2080Ti / AMD 3990x Threadripper workstation, I found that the Firefox version maintains a similar frame rate of 30fps (without Smooth Motion) for the [Flying Over Norway (4K UHD) ](https://www.youtube.com/watch?v=46S-IZWQ7Q0)video, while Chrome reports a smooth 60fps (with Smooth Motion).

[Video Test (1x Speed)](https://www.youtube.com/watch?v=KtcQPWuZnN0)

Running the videos at 2x speed, they also run similarly, dropping only a few frames here and there.

[Video Test (2x Speed)](https://www.youtube.com/watch?v=JPL-tbX0C6s)

Here are the Ambilight settings used for the two browsers for these tests.

![chrome-firefox](https://user-images.githubusercontent.com/19179570/158105249-43d91da7-8097-4b4e-a812-79f6f5e03826.png)

Thank you for you work @WesselKroos, excited to see it on the Firefox Addons Store soon!

**Comment by WesselKroos** [comment] 2022-03-15 20:59
Nice to hear that it works a lot better!
Seems like I'll have to restore the smooth motion setting in WebGL mode. 
And there are still some parts in the WebGL rendering pipeline that I'll improve as well in the next weeks, to make sure that I squeeze out all the performance potential there is.

Btw, I'll probably remove the Resolution and Antialiasing settings once I've fully implemented WebGL. Because those values can be automatically optimized based on the user defined values of other settings combined with the resolution of the video. There is no need to bother the user with the complexity of finetuning those values per video.

**Comment by WesselKroos** [comment] 2022-04-24 12:53
It took a while to finished the implementation. WebGL requires a lot more maintenance than the current rendering method. (Catching edge cases like: Release the GPU control and memory when the tab is invisible, 
Restart when the GPU crashes, Restart when the browser kills WebGL, Apply a workaround when the video src comes from googlevideo.com instead of youtube.com, etc...)

The rollout will happen gradually because I want to resolve any issues before it gets enabled by default:
1. Till 27th of april: Testing
2. 27th of april: Release 2.36.21 - Contains the setting to enable WebGL
3. ~End of may: Release 2.36.22 - WebGL will be enabled for 20% of the current users and all new users
4. ~End of june: Release 2.36.23 - WebGL enabled by default for everyone
5. ~Beginning of june: Firefox release

**Comment by Deagan** [comment] 2022-04-25 03:51
After testing 2.36.21 on Firefox for a bit with the same settings, and same [Flying Over Norway (4K UHD)](https://www.youtube.com/watch?v=46S-IZWQ7Q0) video, I found that performance is still great!

Without WebGL, Ambilight video plays at around 19FPS, and with WebGL on, Ambilight plays around 2x better, at around 60FPS!

That said, my computer is quite powerful, so "acceptable performance" would still depend on the power of an average user's system, but I assume as long as they aren't pushing this many streams of 4K video at 2x speed, they will be just fine. I wouldn't stress too much about the frame rate of Ambilight, as long as the video itself is playable. Even if Ambilight performs at a lower frame rate, it seems that the video content itself plays at full frame rate, which is great!

Still, it's awesome that you're optimizing WebGL for various view modes and possible crashes. I'm sure with your continued dedication, it will become even more perfect with time!

Smooth Motion is also working as expected without jutter or flicker, and I would be happy to use this version as-is on Firefox as a daily driver.

I hope to see it on the Firefox Addon Store, sooner rather than later (because I'm using the temporary addon debug method to install for now).

Thanks again for all your time and hard work @WesselKroos! 🚀👽💕

**Comment by WesselKroos** [comment] 2022-05-26 11:47
The extension is back in the Firefox Addons store: https://addons.mozilla.org/addon/ambient-light-for-youtube/

Thanks for the beta testing and enjoy!

**Closed** 2022-05-26 11:47 UTC
Labels: T: Enhancement, P: High, B: Firefox, S: In review

**Comment by Deagan** [comment] 2022-05-27 07:10
> The extension is back in the Firefox Add-ons store: https://addons.mozilla.org/addon/ambient-light-for-youtube/
> 
> Thanks for the beta testing and enjoy!

Thank you so much @WesselKroos! It's working great on Firefox.

I don't want to overreach, but any ideas on making this work with Librewolf? It is a privacy fork of Firefox that should allow the extension to work, but for whatever reason it doesn't show the Ambilight button or effect on videos. I think it may have something to do with User Agents, but that's a shot in the dark, as far as I know, Librewolf should function just like Firefox.

**Comment by WesselKroos** [comment] 2022-05-27 09:24
I'm not checking user agents before I enable the Ambient light extension. I only use features detection to enable features and check the user agent to turn on workarounds.

I think what's holding the extension from functioning is that it uses canvas and WebGL, but both seem to be disabled by default in LibreWolf: https://librewolf.net/docs/faq/#should-i-allow-canvas-access-how-do-i-do-it

**Comment by Deagan** [comment] 2022-05-27 11:04
Yes, Canvas/Fingerprinting/WebGL can be turned on/off in LibeWolf settings, and using the Librewolf.cfg file. It seems that even with an empty Librewolf.cfg, negating all privacy tweaks, Ambilight doesn't work. /:

The latest version I have looks to be 2.36.25, and when I "Load Temporary Addon..." that, it works as expected in LibreWolf.

I guess there must have been a change in 2.36.26 that makes it stop working for some reason. I have looked at the commits, but I am not technically savvy code-wise to troubleshoot properly.

Was there any easy way for me to troubleshoot using the Web Console or something? I wish I could be of better help, I'm not sure what could have disabled the Addon between those two versions.

**Comment by Deagan** [comment] 2022-05-27 11:04
Yes, Canvas/Fingerprinting/WebGL can be turned on/off in LibeWolf settings, and using the Librewolf.cfg file. It seems that even with an empty Librewolf.cfg, negating all privacy tweaks, Ambilight doesn't work. /:

The latest version I have looks to be 2.36.25, and when I "Load Temporary Addon..." that, it works as expected in LibreWolf.

I guess there must have been a change in 2.36.26 that makes it stop working for some reason. I have looked at the commits, but I am not technically savvy code-wise to troubleshoot properly.

Was there any easy way for me to troubleshoot using the Web Console or something? I wish I could be of better help, I'm not sure what could have disabled the Addon between those two versions.

**Comment by Deagan** [comment] 2022-05-27 11:15
I made a comment about the getBrowser function here:
https://github.com/WesselKroos/youtube-ambilight/commit/8b8dbda0ce3c0ae377fa0cb75d1b4ec6eb5de3c7#r74667859

I'm not sure, hopefully you can think of a quick fix, I still think (with my limited knowledge) that it may have something to do with identifying the browser.

**Comment by WesselKroos** [comment] 2022-05-27 12:51
Apparently LibreWolf has not implemented chrome.storage.local.onChanged. I will catch the error and display a warning to the user to manually synchronize the crash options. The fix will land in the next version.

**Comment by Deagan** [comment] 2022-05-28 02:25
Interesting, so it was related to the Extension Storage changes, and you were able to make it functional on LibreWolf again?

Does this mean that the extension will now recognize if it can/can't store data in Extension Storage, prompt the user, then revert to Local Storage/Cookies as a failsafe?

Thank you for troubleshooting and finding a fix, I know these have been niche requests!

**Comment by WesselKroos** [comment] 2022-05-28 08:55
> you were able to make it functional on LibreWolf again?

Yes

> ... and revert to Local Storage/Cookies as a failsafe?

No, it's less severe luckily. Extension storage still works. Only the synchronization of any crash report settings changes from the options popup to open /watch tabs doesn't work.

**Comment by Deagan** [comment] 2022-05-28 11:05
Yay, you're awesome! Thank you for everything, I am excited to finally have a privacy-hardened and secure browser, with a beautiful YouTube player, and it's all because of you!
