### ISSUE TITLE
Please add Twitch support for the YouTube Ambilight addon

### ISSUE THREAD

**Issue by ByNetsky** [WesselKroos/youtube-ambilight#216] opened 2024-01-30 21:18 UTC
I hope this message finds you well. First of all, I would like to express my appreciation for your great work on the YouTube Ambilight addon. It's really impressive how it enhances the visual experience when watching videos on YouTube.

I'm an avid user of your addon and wanted to let you know that it's a real game changer for me and I'm sure many other users. The atmosphere it creates is truly unique and adds significantly to the immersion during video streaming.

I can imagine that the integration of this addon with Twitch would be a revolutionary development. Many of us not only spend time on YouTube, but also on Twitch to watch live streams from our favorite creators. The ability to enjoy the Ambilight experience on Twitch would undoubtedly appeal to a wider and more enthusiastic user base.

**Comment by WesselKroos** [comment] 2024-01-31 10:59
Duplicate of #211

**Closed** 2024-01-31 10:59 UTC
Labels: T: Enhancement, S: Todo
