### ISSUE TITLE
Support for other platforms? (Hulu, Netflix, etc.)

### ISSUE THREAD

**Issue by epiqu1n** [WesselKroos/youtube-ambilight#214] opened 2024-01-29 00:20 UTC
Would it be possible to add support for other video streaming sites? I've been using Ambient Light to help even wear on my ultrawide OLED while watching YouTube content, and I'd love to be able to do the same with Netflix and Hulu.

**Comment by WesselKroos** [comment] 2024-01-29 11:11
Duplicate of #112

**Closed** 2024-01-29 11:12 UTC
Labels: T: Enhancement, S: Todo
