### ISSUE TITLE
Settings reset after each update

### ISSUE THREAD

**Issue by Luke0094** [WesselKroos/youtube-ambilight#259] opened 2024-09-05 11:48 UTC
### Bug description

As title, after each update settings are lost and need to be loaded again, this is especially noticeable with black bar since is still an experimental feature that might cut partially the video.

### Steps to reproduce the behavior

As above.

### Browser

Chrome

### Operating system

Windows

### Extension version

2.38.10

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/28f51e79-2199-4e0b-acb9-a1d48d62bb77">
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/42f1f387-a4d3-4a9c-841c-2b82a9d3d15b">

**Comment by WesselKroos** [comment] 2024-09-05 15:47
I'm unable to reproduce this issue.
The extension data is coupled to your browser's extension storage, so I'm not doing anything special to migrate these settings.

Could you clarify:
1. When this happend
2. From which to which extension version update this happend
3. If possible, create a screenrecording of the settings being reset after an update

**Comment by Luke0094** [comment] 2024-09-05 16:07
This happen quite frequently since the first time I've installed the extensions (been a while now), not sure if is about update, cache cleaning or what then however I have no problem with all other my extensions, just this one that apparently every few weeks looses settings, the only reason I'm noticing this issue is cause the "remove black bar" that happen to be again enabled, I'm not even sure if looses all settings or just this particular one.
I apologize if I'm unable to provide more clarifications.

**Comment by WesselKroos** [comment] 2024-09-05 16:14
Maybe you're often switching account's/signin out/logging back into your Google Chrome account. You can use the import from/export to cloud storage feature to save and restore your settings:

![image](https://github.com/user-attachments/assets/2d350586-6f69-4700-adfd-40111a153592)

**Comment by Luke0094** [comment] 2024-09-05 16:18
Ar, i'll check with this setting.

**Comment by WesselKroos** [comment] 2024-09-05 17:03
Could you give some extensions for which you have not had this problem?

**Comment by Luke0094** [comment] 2024-09-05 17:17
For exemple Enhancer for YouTube, SponsorBlock per YouTube, AdGuard and Dark Reader that all uses stored settings.
The only thing I can think is that AdGuard with his settings may delete cookies ineherent also to this extensions but is weird.

**Comment by WesselKroos** [comment] 2024-09-06 17:40
Strange. There is also a reset-all-settings button in the top right of the menu. But I doubt that you've clicked that button, since it pops up a confirmation dialog before deleting all your settings.
![image](https://github.com/user-attachments/assets/56c0cb3a-c148-4ea9-a3ef-1013c14b7676)

So I'm not sure how I could help you further with this issue to be honest.
Is it ok if I close this issue until you've found the steps to reproduce it (or when more users report this problem)?

**Comment by Luke0094** [comment] 2024-09-06 20:03
It's ok you can close it, is an unfortunate issue, since is a random behavior not sure what i can do on my part.

**Closed** 2024-09-06 20:12 UTC
Labels: T: Bug, S: On hold (More info required)
