### ISSUE TITLE
Nvidia RTX HDR video enhancement cannot be activated if Ambient Light is enabled.

### ISSUE THREAD

**Issue by ccresz** [WesselKroos/youtube-ambilight#215] opened 2024-01-30 03:06 UTC
### Bug description

You can see that as soon as Ambient Light is enabled or disabled the oposite happens to HDR and Super Resolution on Nvidia Control Panel

### Steps to reproduce the behavior

1. Follow the Nvidia info on their page to make sure you have a compatible graphics card, in my case I'm using a 4070ti
2. Make sure you have an HDR10 capable monitor, in my case I have an Alienware AW3423DWF
3. Get the latest drivers from Nvidia RTX HDR > 551.23
4. Go to your windows settings and make sure Chrome or Edge are set to run on the high performance graphics card if you have integrated graphics.
5. Open Nvidia control panel and enable HDR video enhancement.
6. Go to chrome play a non HDR video, disable _ambient light_ from the video controls area and see how on the Nvidia control panel it shows _Active_ on the HDR video enhancement.
7. Enable Ambient Light without pausing the video and you'll see how the video loses the HDR enhancements and Nvidia control panel showes the enhancement as _Inactive._

### Browser

Chrome, Microsoft Edge

### Operating system

Windows

### Extension version

 2.38.1

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

https://github.com/WesselKroos/youtube-ambilight/assets/25826780/8df8781f-d507-4a66-9a11-07fd560b3efc

**Comment by WesselKroos** [comment] 2024-01-30 07:31
Duplicate of #202

**Closed** 2024-01-30 07:31 UTC
Labels: T: Bug, S: Todo
