### ISSUE TITLE
Glitchy vertical video effect

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#150] opened 2023-01-23 19:27 UTC
## Describe the bug
If the extension thinks that the video is vertical, even if there are bits in the corner, it will try to apply the ambient effect
Making the video full-screen will trigger a glitch that squizzes the video

## To reproduce
1. Go to a [video](https://www.youtube.com/watch?v=Ijo76dLmK-I)
2. Enable the effect on vertical videos (<kbd>V</kbd>)
3. Go to full screen (<kbd>F</kbd>)

## Expected behavior
Apply the effect as it'd be applied in non-full-screen mode

## Video
https://user-images.githubusercontent.com/6422804/214131118-6cf4a4a7-53e8-426d-82f8-bbe49fe3933f.mp4

## Desktop (please complete the following information):
 - OS: Windows 10 Pro 22H2
 - Browser: Brave
 - Browser version: 1.47.171 
 - Extension version: 2.36.33

## Other extensions:
Does the bug still persist when you disable all other extensions? If not, which other extension conflicts with the Ambient light for YouTube extension? **Haven't tried**

**Comment by WesselKroos** [comment] 2023-01-23 20:03
I can't seem to reproduce this issue. Can you try to reproduce it yourself with all other extensions disabled?

**Comment by avi12** [comment] 2023-01-23 20:24
Yes
I reproduced it even after disabling all non-YouTube extensions

**Comment by WesselKroos** [comment] 2023-01-23 21:59
Strange, maybe YouTube is A/B testing a html/css update. Can you post a screenshot of the html and the logs in the Javascript console when it is in that incorrect state?

**Comment by avi12** [comment] 2023-01-23 22:02
That's interesting. I just discovered that if I scroll down a little, the issue gets resolved

**Comment by avi12** [comment] 2023-01-23 22:04
![image](https://user-images.githubusercontent.com/6422804/214160166-5dd2530d-de0d-4452-b9d9-27c60474541d.png)

**Comment by WesselKroos** [comment] 2023-01-24 17:11
@avi12 I can't find the video tag in your screenshot. Is the video tag in the `ytp-iv-video-content` class? It's in the `html5-video-container` class for me.

**Comment by avi12** [comment] 2023-01-24 19:31
The top highlighted is the `<video>`, and the bottom one is what happens when I use the element picker and move the mouse a bit to the left/right
![image](https://user-images.githubusercontent.com/6422804/214390202-053e83e1-f65e-49b9-9b1a-47d42e9aeb39.png)

**Comment by WesselKroos** [comment] 2023-01-26 17:57
I have the same style properties as in your devtools screenshot. The only difference is that I have a 1440p resolution and there are slightly different `transform` values but those are within an expected margin of error:
![image](https://user-images.githubusercontent.com/31220528/214911037-e77a8085-2386-4b6c-8b54-9536679b8875.png)

I suspect that there is sometimes another stylesheet or style attribute value applied with an override of the `transform` css property on your `video` tag. Because the `html5-video-container` tag is correctly scaled down by the `scale(0.4504, 1)` transformation and the `video` tag is correctly scaled up by the `scale(2.22, 1)` transformation defined in the `--video-transform` variable.

**Comment by WesselKroos** [comment] 2023-01-28 19:02
@avi12 I was finally able to reproduce this bug by trying out a different browsers. There seems to be a rendering bug in a specific version of chromium. The reason I was unable to reproduce this was because my Brave browser was not yet updated to the version with the rendering bug.

A workaround seems to be to apply the css property `opacity: 0.99` to the video tag. Which hints to a rendering bug in Chromium since that has nothing to do with the transformation itself.

I'll try to find another workaround than the opacity property that does not have any visual impact to the video and report this bug to the Chromium developers.

**Comment by avi12** [comment] 2023-01-28 19:13
I usually don't watch videos on full screen so it's not a big issue, but I appreciate that you're trying to fix it 🙏

**Comment by WesselKroos** [comment] 2023-01-28 22:56
@avi12 Your report is greatly appreciated because it looks like more users will see this bug in the future. This bug seems to be introduced since Chromium 107. And the actual reason why I was not able to reproduce it is because I have a custom flag enabled in Chrome. 

So I'm 2 Chromium versions late at the moment, but I'll find a fix! 😄

**Comment by WesselKroos** [comment] 2023-01-29 22:17
@avi12 This is now fixed in version 2.37.2 (Already released to Opera but in review for Edge and Chrome)

**Closed by WesselKroos** 2023-01-29 22:17 UTC
Labels: T: Bug, S: Ready for release, P: High, B: Chromium
