### ISSUE TITLE
Video framerate drop on high framerate videos

### ISSUE THREAD

**Issue by aspidxt** [WesselKroos/youtube-ambilight#114] opened 2022-05-19 18:16 UTC
When I try to play any 50 fps video with ambilight enabled framerate drops (`display` value on fps monitor) to 8-12 frames, and droped frames counter increases. CPU and GPU usage at ~60% though 

My config:
Laptop Lenovo E480
CPU i7-8550U
GPU RX550
16gb
Ext display at  3440x1440@60hz

Windows 10
Vivaldi 5.2
GL render enabled (resolution change didn't heps)
Rest of settings are defaults

**Comment by WesselKroos** [comment] 2022-05-19 19:25
My laptop is also not able to play videos with ambient light beyond 30 fps without frame drops. But you can decrease the gpu usage by limiting the ambient light framerate to 30 fps via the settings. For my laptop that works good enough to prevent video frame drops.

Also, what resolution is your display and the video that is playing? 

And what cpu and gpu usage do you get when you disable black bar detection, enable WebGL, turn the resolution down to 6.25%, limit the framerate to 30 fps and set the blur to 0? That gives me an idea of the best possible cpu and gpu usage we can achieve on your laptop.

**Comment by WesselKroos** [comment] 2022-05-19 19:34
Hmm, looking at the benchmark scores online the RX550 should easily be able to play high framerate videos with ambient light. Are you sure that hardware acceleration is enabled in the browser? What performance do you get in Edge or Chrome?

**Comment by WesselKroos** [comment] 2022-05-26 11:51
@aspidxt I'll close this issue in 4 days if you've still not responded by then.

**Comment by aspidxt** [comment] 2022-05-26 11:56
![image](https://user-images.githubusercontent.com/29504662/170482992-d664bd2a-04d6-49bc-ae5b-d8945e251a40.png)
sry, miss notification
All accelerations are on, I also forced to use ext gpu in windows
![image](https://user-images.githubusercontent.com/29504662/170483393-b8df9fbb-5c8b-47d6-ba08-0499025f09fd.png)

**Comment by WesselKroos** [comment] 2022-05-26 12:23
No problemo.
Hmm... The vivaldi://gpu page does indeed looks correct.

Can you post screenshots of the Task Manager's performance tab that contains the CPU and GPU usage on a:
1. 50fps video & ambient light disabled
2. 50fps video & ambient light enabled
3. 25fps video & ambient light disabled
4. 25fps video & ambient light enabled

**Comment by aspidxt** [comment] 2022-05-26 12:37
![image](https://user-images.githubusercontent.com/29504662/170488634-eb5a82e7-9c37-4e89-84f6-a8f3cc7848f7.png)
![image](https://user-images.githubusercontent.com/29504662/170489087-3a3d03b9-e362-4362-8432-5e682c3bcdb6.png)

**Comment by aspidxt** [comment] 2022-05-26 12:45
25fps OFF
![image](https://user-images.githubusercontent.com/29504662/170490078-a4f43e4a-1d97-4581-9ae4-b8d6a5386275.png)

25fps ON
![image](https://user-images.githubusercontent.com/29504662/170489794-8b879c99-ba44-433f-bf68-152b5f33b9bc.png)

**Comment by WesselKroos** [comment] 2022-05-26 13:01
Correct me if I'm wrong. But if I read the data correctly then the ambient light effect is costing you in 60fps mode:
- 0% CPU usage (From 50% to still 50%)
- 22% GPU usage (From 33% to 55%)

There is nothing that I can do to fix the CPU usage because that's just the CPU usage the Vivaldi browser needs to play the video itself. And the 22% GPU usage is an expected cost to display the ambient light effect. 

But what I can also see is that the Intel UHD Graphics is decoding the video (because the Video Decoding chart of the Radeon RX 550 is empty) and the Radeon RX 550 is displaying the ambient light effect (that is the 3D chart). That means that every video frame is being copied from the Intel GPU to the AMD GPU. A more optimal path could be 2 things:
- The intel GPU decodes the video and displays the ambient light effect
- The AMD GPU decodes the video and displays the ambient light effect
So that this copying step between the GPU's can be skipped. I wouldn't be surprised if that will also decrease the usage in the 3D chart.

I don't know yet how you can force the video decoding to the AMD GPU. But I think you can at least move the usage on the AMD 3D chart to the Intel GPU by switching the Windows 10 Graphics settings for Vivaldi to **Power saving** and then restart the browser. Can you post a screenshot of the Intel and AMD GPU's usage with **Power saving** enabled?

**Comment by aspidxt** [comment] 2022-05-26 13:14
Video decode chart is empty on intel as well
![image](https://user-images.githubusercontent.com/29504662/170493834-43b64e64-fc5b-4415-a67f-89f83e0229c1.png)
I think Intel gpu will be loaded anyway as it's connected to hardware hdmi port, if I disable perf mode it's will not play 4k videos.

It's weird for me to see 50% load on both `3d` and `copy` (don't actually know what it means:) charts

**Comment by WesselKroos** [comment] 2022-05-26 13:16
Ok, I found something for the second option. You can disable the integrated GPU this way:
1. Go into the **Device Manager**
2. Go to **Display adapters > Intel (R) UHD Graphics**
3. Right click to and click **Disable device**
4. Your screen will flicker for a bit and then it has completely switched over to the dedicated AMD GPU

That should move all the processes to the AMD Radeon RX 550.

**Comment by WesselKroos** [comment] 2022-05-26 13:23
> Video decode chart is empty on intel as well
Ah, that means that your CPU is decoding the video. 
I also have a laptop with Intel UHD Graphics 620, but without a dedicated GPU. Let me check what I do to run 60 fps video's without framedrops.

**Comment by WesselKroos** [comment] 2022-05-26 14:02
So yeah, I have the Intel i7-8650U (A number 100 higher than yours) without a dedicated AMD GPU. 
I'm running with the same ambient light settings and these are my usage charts without video frame drops (Except for a few at the start of every the video) on this video https://www.youtube.com/watch?v=VnLdOcDNTe0

1440p 60fps video, 30fps ambient light, 25% resolution:
![image](https://user-images.githubusercontent.com/31220528/170501043-8f3c02a6-187f-469c-ad02-0c0eb992ff7d.png)
Temperature: ~70 degrees

1440p 60fps video, 30fps ambient light, 100% resolution:
![image](https://user-images.githubusercontent.com/31220528/170501323-9b1cb34e-7906-466c-9a6b-ed7c893d1193.png)
Temperature: ~80 degrees

1440p 60fps video, 60fps ambient light, 100% resolution:
![image](https://user-images.githubusercontent.com/31220528/170502028-1ee62677-a94e-4a03-ae6b-81a95522087f.png)
Temperature: ~85 degrees

So I think the framedrops are caused by the switchable graphics between the integrated and the dedicated GPU's. I expect that disabling one or the other should fix it.

**Comment by aspidxt** [comment] 2022-06-13 07:28
@WesselKroos at first I can't use all displays as I disable Intel GPU, also performance is worse. I suppose now this is issue of my hardware/drivers, I saw more lags in different apps, with cpu/gpu load below 80%.
Thanks for your help, and I think you can close this issue

**Closed** 2022-06-13 08:25 UTC
Labels: S: More info required, T: Performance
